### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by DaHui21** [mflink3012/spaceengineers-ingamescript-cargowatch#1]
I am trying to use the script to monitor cargo and turn on/off a light when the watermark is reached... I am not sure if I am using the script correctly or if it no longer works... The block names I am using keep saying "Not Found". I have been going into the script code and editing the values in the script... is this correct? There is really no information on how to use the script properly

**Comment by mflink3012** [comment]
Please see the README.md.
There is a section about custom properties. You have to put the properties as defined in this section into the custom properties of the programming block where you pasted the script into.
